"""Markdown writer with YAML frontmatter (TTRG convention)."""

from __future__ import annotations

import os
from datetime import datetime
from typing import Optional, List, Dict, Any


def write_trade_note(
    out_path: str,
    trade: Dict[str, Any],
    tags: Optional[List[str]] = None,
) -> str:
    """Write a single trade note to out_path. Creates parent dirs.

    Returns the path written.
    """
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    symbol = trade.get("symbol", "UNKNOWN")
    side = trade.get("side", "LONG")
    pnl = float(trade.get("pnl", 0.0))
    pnl_pct = float(trade.get("pnl_pct", 0.0))
    entry_price = float(trade.get("entry_price", 0.0))
    exit_price = float(trade.get("exit_price", 0.0))
    qty = float(trade.get("qty", 0.0))
    notional = float(trade.get("notional", entry_price * qty))
    duration = int(trade.get("duration_bars", 0))
    reason = trade.get("exit_reason", "manual")
    entry_time = trade.get("entry_time", "")
    exit_time = trade.get("exit_time", "")
    z_score = float(trade.get("z_score", 0.0))
    ema_slope = float(trade.get("ema_slope", 0.0))
    ml_conf = float(trade.get("ml_confidence", 0.0))
    commission = float(trade.get("commission", 0.0))
    gross = float(trade.get("gross_pnl", pnl + commission))

    today = datetime.now().strftime("%Y-%m-%d")
    frontmatter_tags = tags or ["trade", "mexc", "scalping", symbol.split("/")[0].lower()]

    content = (
        "---\n"
        f"tags: [{', '.join(frontmatter_tags)}]\n"
        f"date: {today}\n"
        f"symbol: {symbol}\n"
        f"side: {side}\n"
        f"pnl: {pnl:.4f}\n"
        f"pnl_pct: {pnl_pct:.3f}\n"
        "---\n"
        f"# Trade — {symbol} {side} @ {entry_price:.4f}\n\n"
        f"**Closed:** {exit_time} | **Duration:** {duration} bars | **Reason:** {reason}\n\n"
        "## Entry\n"
        f"- Price: {entry_price:.4f} | Qty: {qty:.4f} | Notional: ${notional:.2f}\n"
        f"- Time: {entry_time}\n"
        f"- Z-score: {z_score:+.2f} | EMA slope: {ema_slope:+.4f}%\n"
        f"- ML ensemble: {ml_conf:.0%} confidence\n\n"
        "## Exit\n"
        f"- Price: {exit_price:.4f} | Commission: ${commission:.4f}\n"
        f"- Reason: `{reason}`\n\n"
        "## P&L\n"
        f"- Gross: ${gross:+.4f} | Commission: -${commission:.4f} | **Net: ${pnl:+.4f} ({pnl_pct:+.2f}%)**\n\n"
        "---\n"
        f"Generated by quant_v2 MEXC Scalper v9 | {datetime.now().isoformat(timespec='seconds')}\n"
    )

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)
    return out_path


def write_daily_summary(
    out_path: str,
    summary: Dict[str, Any],
    tags: Optional[List[str]] = None,
) -> str:
    """Write a daily P&L summary to out_path. Creates parent dirs."""
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    today = summary.get("date", datetime.now().strftime("%Y-%m-%d"))
    n_trades = int(summary.get("trades", 0))
    wins = int(summary.get("wins", 0))
    losses = int(summary.get("losses", 0))
    win_rate = float(summary.get("win_rate", 0.0))
    gross = float(summary.get("gross_pnl", 0.0))
    commission = float(summary.get("commission", 0.0))
    net = float(summary.get("net_pnl", 0.0))
    net_pct = float(summary.get("net_pnl_pct", 0.0))
    pairs = summary.get("pairs", {})
    best = summary.get("best_trade", {})
    worst = summary.get("worst_trade", {})
    capital = float(summary.get("capital_start", 18.0))
    capital_end = float(summary.get("capital_end", capital + net))
    pf = float(summary.get("profit_factor", 0.0))

    frontmatter_tags = tags or ["kpi", "daily", "mexc", "scalping"]

    pairs_rows = ""
    if pairs:
        for sym, p in pairs.items():
            pairs_rows += f"| {sym} | {p.get('trades', 0)} | ${p.get('pnl', 0.0):+.4f} | {p.get('win_rate', 0.0)*100:.1f}% |\n"
    else:
        pairs_rows = "| — | 0 | $0.00 | 0% |\n"

    best_section = "—"
    if best:
        best_section = (
            f"{best.get('symbol', '?')} {best.get('side', '?')} → "
            f"${best.get('pnl', 0.0):+.4f} ({best.get('pnl_pct', 0.0):+.2f}%)"
        )

    worst_section = "—"
    if worst:
        worst_section = (
            f"{worst.get('symbol', '?')} {worst.get('side', '?')} → "
            f"${worst.get('pnl', 0.0):+.4f} ({worst.get('pnl_pct', 0.0):+.2f}%)"
        )

    content = (
        "---\n"
        f"tags: [{', '.join(frontmatter_tags)}]\n"
        f"date: {today}\n"
        f"trades: {n_trades}\n"
        f"net_pnl: {net:.4f}\n"
        "---\n"
        f"# MEXC Scalper — Daily Summary {today}\n\n"
        f"**Capital:** ${capital:.2f} → ${capital_end:.2f} ({net_pct:+.2f}%)\n\n"
        "## Performance\n\n"
        "| Metric | Value |\n"
        "|---|---|\n"
        f"| Trades | {n_trades} |\n"
        f"| Wins | {wins} |\n"
        f"| Losses | {losses} |\n"
        f"| Win Rate | {win_rate*100:.1f}% |\n"
        f"| Gross P&L | ${gross:+.4f} |\n"
        f"| Commission | -${commission:.4f} |\n"
        f"| **Net P&L** | **${net:+.4f}** |\n"
        f"| Net Return | {net_pct:+.2f}% |\n"
        f"| Profit Factor | {pf:.2f} |\n\n"
        "## Per-Pair Breakdown\n\n"
        "| Symbol | Trades | P&L | Win Rate |\n"
        "|---|---|---|---|\n"
        f"{pairs_rows}"
        "\n"
        f"**Best Trade:** {best_section}\n\n"
        f"**Worst Trade:** {worst_section}\n\n"
        "---\n"
        f"Generated by quant_v2 MEXC Scalper v9 | {datetime.now().isoformat(timespec='seconds')}\n"
    )

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)
    return out_path


def write_kpi_to_vault_root(
    out_path: str,
    summary: Dict[str, Any],
) -> str:
    """Write a TTRG-convention KPI report to 30-KPI/YYYY-MM-DD.md."""
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    today = summary.get("date", datetime.now().strftime("%Y-%m-%d"))
    n_trades = int(summary.get("trades", 0))
    wins = int(summary.get("wins", 0))
    losses = int(summary.get("losses", 0))
    win_rate = float(summary.get("win_rate", 0.0))
    net = float(summary.get("net_pnl", 0.0))
    net_pct = float(summary.get("net_pnl_pct", 0.0))
    pf = float(summary.get("profit_factor", 0.0))

    content = (
        "---\n"
        "tags: [kpi, weekly, mexc]\n"
        f"date: {today}\n"
        "---\n"
        f"# KPI Report — {today} (MEXC Scalper)\n\n"
        "## Trading KPIs\n\n"
        "| Metric | Value |\n"
        "|---|---|\n"
        f"| Trades | {n_trades} |\n"
        f"| Wins / Losses | {wins} / {losses} |\n"
        f"| Win Rate | {win_rate*100:.1f}% |\n"
        f"| Net P&L | ${net:+.4f} |\n"
        f"| Return | {net_pct:+.2f}% |\n"
        f"| Profit Factor | {pf:.2f} |\n\n"
        f"## Project\n"
        f"- Project: MEXC-Quant-Trading\n"
        f"- Strategy: v9-trend-following\n"
        f"- Capital: ${summary.get('capital_start', 18.0):.2f}\n\n"
        f"## Source\n"
        f"- [[10-Projects/MEXC-Quant-Trading/daily-summaries/{today}|Daily Summary]]\n"
        f"- [[10-Projects/MEXC-Quant-Trading/index|MEXC Project]]\n\n"
        "---\n"
        f"Generated by quant_v2/obsidian/daily_summary.py | {datetime.now().isoformat(timespec='seconds')}\n"
    )

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)
    return out_path
